export const indianStations = [
  { code: 'NDLS', name: 'New Delhi', state: 'Delhi', platforms: 16, zone: 'NR' },
  { code: 'MMCT', name: 'Mumbai Central', state: 'Maharashtra', platforms: 9, zone: 'WR' },
  { code: 'CSMT', name: 'Chhatrapati Shivaji Maharaj Terminus', state: 'Maharashtra', platforms: 18, zone: 'CR' },
  { code: 'HWH', name: 'Howrah Junction', state: 'West Bengal', platforms: 23, zone: 'ER' },
  { code: 'SBC', name: 'KSR Bengaluru City', state: 'Karnataka', platforms: 10, zone: 'SWR' },
  { code: 'MAS', name: 'MGR Chennai Central', state: 'Tamil Nadu', platforms: 17, zone: 'SR' },
  { code: 'ADI', name: 'Ahmedabad Junction', state: 'Gujarat', platforms: 12, zone: 'WR' },
  { code: 'PNBE', name: 'Patna Junction', state: 'Bihar', platforms: 10, zone: 'ECR' },
  { code: 'UD', name: 'Udupi', state: 'Karnataka', platforms: 3, zone: 'KR' },
  { code: 'JAT', name: 'Jammu Tawi', state: 'Jammu & Kashmir', platforms: 5, zone: 'NR' },
  { code: 'JP', name: 'Jaipur Junction', state: 'Rajasthan', platforms: 7, zone: 'NWR' },
  { code: 'HYB', name: 'Hyderabad Deccan Nampally', state: 'Telangana', platforms: 6, zone: 'SCR' },
  { code: 'SC', name: 'Secunderabad Junction', state: 'Telangana', platforms: 10, zone: 'SCR' },
  { code: 'CNB', name: 'Kanpur Central', state: 'Uttar Pradesh', platforms: 10, zone: 'NCR' },
  { code: 'GKP', name: 'Gorakhpur Junction', state: 'Uttar Pradesh', platforms: 10, zone: 'NER' },
  { code: 'BSB', name: 'Varanasi Junction', state: 'Uttar Pradesh', platforms: 9, zone: 'NR' },
  { code: 'LKO', name: 'Lucknow Charbagh NR', state: 'Uttar Pradesh', platforms: 9, zone: 'NR' },
  { code: 'CBE', name: 'Coimbatore Junction', state: 'Tamil Nadu', platforms: 6, zone: 'SR' },
  { code: 'TVC', name: 'Thiruvananthapuram Central', state: 'Kerala', platforms: 5, zone: 'SR' },
  { code: 'GHY', name: 'Guwahati Junction', state: 'Assam', platforms: 7, zone: 'NFR' },
  { code: 'BPL', name: 'Bhopal Junction', state: 'Madhya Pradesh', platforms: 6, zone: 'WCR' },
  { code: 'PUNE', name: 'Pune Junction', state: 'Maharashtra', platforms: 6, zone: 'CR' },
  { code: 'NGP', name: 'Nagpur Junction', state: 'Maharashtra', platforms: 8, zone: 'CR' },
  { code: 'BBS', name: 'Bhubaneswar', state: 'Odisha', platforms: 6, zone: 'ECoR' },
  { code: 'VSKP', name: 'Visakhapatnam Junction', state: 'Andhra Pradesh', platforms: 8, zone: 'ECoR' },
  { code: 'BZA', name: 'Vijayawada Junction', state: 'Andhra Pradesh', platforms: 10, zone: 'SCR' },
  { code: 'ASR', name: 'Amritsar Junction', state: 'Punjab', platforms: 7, zone: 'NR' },
  { code: 'CDG', name: 'Chandigarh Junction', state: 'Union Territory', platforms: 6, zone: 'NR' },
  { code: 'LTT', name: 'Lokmanya Tilak Terminus', state: 'Maharashtra', platforms: 5, zone: 'CR' },
  { code: 'KYN', name: 'Kalyan Junction', state: 'Maharashtra', platforms: 8, zone: 'CR' },
  { code: 'BDTS', name: 'Bandra Terminus', state: 'Maharashtra', platforms: 7, zone: 'WR' },
  { code: 'TATA', name: 'Tatanagar Junction', state: 'Jharkhand', platforms: 6, zone: 'SER' },
  { code: 'KGP', name: 'Kharagpur Junction', state: 'West Bengal', platforms: 12, zone: 'SER' },
  { code: 'SDAH', name: 'Sealdah', state: 'West Bengal', platforms: 21, zone: 'ER' },
  { code: 'KOAA', name: 'Kolkata', state: 'West Bengal', platforms: 5, zone: 'ER' },
  { code: 'MS', name: 'Chennai Egmore', state: 'Tamil Nadu', platforms: 11, zone: 'SR' },
  { code: 'MDU', name: 'Madurai Junction', state: 'Tamil Nadu', platforms: 8, zone: 'SR' },
  { code: 'ERS', name: 'Ernakulam Junction', state: 'Kerala', platforms: 6, zone: 'SR' },
  { code: 'AGC', name: 'Agra Cantt', state: 'Uttar Pradesh', platforms: 6, zone: 'NCR' },
  { code: 'VGLJ', name: 'VGL Jhansi Junction', state: 'Uttar Pradesh', platforms: 8, zone: 'NCR' },
  { code: 'KOTA', name: 'Kota Junction', state: 'Rajasthan', platforms: 4, zone: 'WCR' },
  { code: 'RTM', name: 'Ratlam Junction', state: 'Madhya Pradesh', platforms: 7, zone: 'WR' },
  { code: 'BRC', name: 'Vadodara Junction', state: 'Gujarat', platforms: 7, zone: 'WR' },
  { code: 'SUR', name: 'Solapur Junction', state: 'Maharashtra', platforms: 5, zone: 'CR' },
  { code: 'ET', name: 'Itarsi Junction', state: 'Madhya Pradesh', platforms: 7, zone: 'WCR' },
  { code: 'JBP', name: 'Jabalpur Junction', state: 'Madhya Pradesh', platforms: 6, zone: 'WCR' },
  { code: 'DDU', name: 'Pt Deen Dayal Upadhyaya Junction', state: 'Uttar Pradesh', platforms: 8, zone: 'ECR' },
  { code: 'GAYA', name: 'Gaya Junction', state: 'Bihar', platforms: 9, zone: 'ECR' },
  { code: 'R', name: 'Raipur Junction', state: 'Chhattisgarh', platforms: 7, zone: 'SECR' },
  { code: 'BSP', name: 'Bilaspur Junction', state: 'Chhattisgarh', platforms: 8, zone: 'SECR' },
  { code: 'DLI', name: 'Old Delhi Junction', state: 'Delhi', platforms: 16, zone: 'NR' },
  { code: 'ANVT', name: 'Anand Vihar Terminal', state: 'Delhi', platforms: 7, zone: 'NR' },
  { code: 'GZB', name: 'Ghaziabad Junction', state: 'Uttar Pradesh', platforms: 6, zone: 'NR' },
  { code: 'DNR', name: 'Danapur', state: 'Bihar', platforms: 6, zone: 'ECR' },
  { code: 'BJU', name: 'Barauni Junction', state: 'Bihar', platforms: 9, zone: 'ECR' },
  { code: 'MFP', name: 'Muzaffarpur Junction', state: 'Bihar', platforms: 6, zone: 'ECR' },
  { code: 'CPR', name: 'Chhapra Junction', state: 'Bihar', platforms: 8, zone: 'NER' },
  { code: 'GWL', name: 'Gwalior Junction', state: 'Madhya Pradesh', platforms: 4, zone: 'NCR' },
  { code: 'UJN', name: 'Ujjain Junction', state: 'Madhya Pradesh', platforms: 8, zone: 'WR' },
  { code: 'INDB', name: 'Indore Junction', state: 'Madhya Pradesh', platforms: 6, zone: 'WR' },
  { code: 'ST', name: 'Surat', state: 'Gujarat', platforms: 4, zone: 'WR' },
  { code: 'ANND', name: 'Anand Junction', state: 'Gujarat', platforms: 6, zone: 'WR' },
  { code: 'NVS', name: 'Navsari', state: 'Gujarat', platforms: 3, zone: 'WR' },
  { code: 'VAPI', name: 'Vapi', state: 'Gujarat', platforms: 3, zone: 'WR' },
  { code: 'BL', name: 'Valsad', state: 'Gujarat', platforms: 3, zone: 'WR' },
  { code: 'YPR', name: 'Yesvantpur Junction', state: 'Karnataka', platforms: 6, zone: 'SWR' },
  { code: 'MYS', name: 'Mysuru Junction', state: 'Karnataka', platforms: 6, zone: 'SWR' },
  { code: 'UBL', name: 'SSS Hubballi Junction', state: 'Karnataka', platforms: 8, zone: 'SWR' },
  { code: 'MAS-S', name: 'Tambaram', state: 'Tamil Nadu', platforms: 8, zone: 'SR' },
  { code: 'TPJ', name: 'Tiruchchirappalli Junction', state: 'Tamil Nadu', platforms: 8, zone: 'SR' },
  { code: 'ED', name: 'Erode Junction', state: 'Tamil Nadu', platforms: 4, zone: 'SR' },
  { code: 'SA', name: 'Salem Junction', state: 'Tamil Nadu', platforms: 5, zone: 'SR' },
  { code: 'TCR', name: 'Thrissur', state: 'Kerala', platforms: 4, zone: 'SR' },
  { code: 'QLN', name: 'Kollam Junction', state: 'Kerala', platforms: 6, zone: 'SR' },
  { code: 'PGT', name: 'Palakkad Junction', state: 'Kerala', platforms: 5, zone: 'SR' },
  { code: 'SRR', name: 'Shoranur Junction', state: 'Kerala', platforms: 7, zone: 'SR' },
  { code: 'AWY', name: 'Aluva', state: 'Kerala', platforms: 3, zone: 'SR' },
  { code: 'RU', name: 'Renigunta Junction', state: 'Andhra Pradesh', platforms: 5, zone: 'SCR' },
  { code: 'TPTY', name: 'Tirupati', state: 'Andhra Pradesh', platforms: 5, zone: 'SCR' },
  { code: 'NLR', name: 'Nellore', state: 'Andhra Pradesh', platforms: 4, zone: 'SCR' },
  { code: 'OGL', name: 'Ongole', state: 'Andhra Pradesh', platforms: 3, zone: 'SCR' },
  { code: 'TEL', name: 'Tenali Junction', state: 'Andhra Pradesh', platforms: 5, zone: 'SCR' },
  { code: 'WL', name: 'Warangal', state: 'Telangana', platforms: 3, zone: 'SCR' },
  { code: 'KZJ', name: 'Kazipet Junction', state: 'Telangana', platforms: 3, zone: 'SCR' },
  { code: 'BPQ', name: 'Balharshah Junction', state: 'Maharashtra', platforms: 5, zone: 'CR' },
  { code: 'SEGM', name: 'Sewagram Junction', state: 'Maharashtra', platforms: 5, zone: 'CR' },
  { code: 'BSL', name: 'Bhusaval Junction', state: 'Maharashtra', platforms: 8, zone: 'CR' },
  { code: 'JSG', name: 'Jharsuguda Junction', state: 'Odisha', platforms: 5, zone: 'SER' },
  { code: 'ROU', name: 'Rourkela Junction', state: 'Odisha', platforms: 5, zone: 'SER' },
  { code: 'CTC', name: 'Cuttack', state: 'Odisha', platforms: 5, zone: 'ECoR' },
  { code: 'BAM', name: 'Brahmapur', state: 'Odisha', platforms: 4, zone: 'ECoR' },
  { code: 'VZM', name: 'Vizianagaram Junction', state: 'Andhra Pradesh', platforms: 5, zone: 'ECoR' },
  { code: 'RJY', name: 'Rajahmundry', state: 'Andhra Pradesh', platforms: 3, zone: 'ECoR' },
  { code: 'SPJ', name: 'Samastipur Junction', state: 'Bihar', platforms: 7, zone: 'ECR' },
  { code: 'DBG', name: 'Darbhanga Junction', state: 'Bihar', platforms: 5, zone: 'ECR' },
  { code: 'GD', name: 'Gonda Junction', state: 'Uttar Pradesh', platforms: 5, zone: 'NER' },
  { code: 'DEC', name: 'Delhi Cantt', state: 'Delhi', platforms: 4, zone: 'NR' },
  { code: 'GNT', name: 'Guntur', state: 'Andhra Pradesh', platforms: 4, zone: 'SCR' },
  { code: 'CCT', name: 'Kakinada Town', state: 'Andhra Pradesh', platforms: 3, zone: 'SCR' },
  { code: 'ATP', name: 'Anantapur', state: 'Andhra Pradesh', platforms: 3, zone: 'SCR' },
  { code: 'NHLN', name: 'Naharlagun', state: 'Arunachal Pradesh', platforms: 2, zone: 'NFR' },
  { code: 'DBRG', name: 'Dibrugarh', state: 'Assam', platforms: 4, zone: 'NFR' },
  { code: 'SCL', name: 'Silchar', state: 'Assam', platforms: 3, zone: 'NFR' },
  { code: 'JTTN', name: 'Jorhat Town', state: 'Assam', platforms: 2, zone: 'NFR' },
  { code: 'LMG', name: 'Lumding', state: 'Assam', platforms: 5, zone: 'NFR' },
  { code: 'NTSK', name: 'New Tinsukia', state: 'Assam', platforms: 4, zone: 'NFR' },
  { code: 'BGP', name: 'Bhagalpur', state: 'Bihar', platforms: 6, zone: 'ER' },
  { code: 'HJP', name: 'Hajipur', state: 'Bihar', platforms: 5, zone: 'ECR' },
  { code: 'DURG', name: 'Durg', state: 'Chhattisgarh', platforms: 5, zone: 'SECR' },
  { code: 'KRBA', name: 'Korba', state: 'Chhattisgarh', platforms: 3, zone: 'SECR' },
  { code: 'RIG', name: 'Raigarh', state: 'Chhattisgarh', platforms: 3, zone: 'SECR' },
  { code: 'MAO', name: 'Madgaon', state: 'Goa', platforms: 4, zone: 'KR' },
  { code: 'VSG', name: 'Vasco-da-Gama', state: 'Goa', platforms: 3, zone: 'SWR' },
  { code: 'THVM', name: 'Thivim', state: 'Goa', platforms: 2, zone: 'KR' },
  { code: 'KRMI', name: 'Karmali', state: 'Goa', platforms: 2, zone: 'KR' },
  { code: 'RJT', name: 'Rajkot', state: 'Gujarat', platforms: 5, zone: 'WR' },
  { code: 'BVC', name: 'Bhavnagar', state: 'Gujarat', platforms: 3, zone: 'WR' },
  { code: 'GNC', name: 'Gandhinagar', state: 'Gujarat', platforms: 3, zone: 'WR' },
  { code: 'JAM', name: 'Jamnagar', state: 'Gujarat', platforms: 3, zone: 'WR' },
  { code: 'UMB', name: 'Ambala Cantt', state: 'Haryana', platforms: 7, zone: 'NR' },
  { code: 'PNP', name: 'Panipat', state: 'Haryana', platforms: 5, zone: 'NR' },
  { code: 'HSR', name: 'Hisar', state: 'Haryana', platforms: 6, zone: 'NWR' },
  { code: 'ROK', name: 'Rohtak', state: 'Haryana', platforms: 3, zone: 'NR' },
  { code: 'KKDE', name: 'Kurukshetra', state: 'Haryana', platforms: 3, zone: 'NR' },
  { code: 'SML', name: 'Shimla', state: 'Himachal Pradesh', platforms: 2, zone: 'NR' },
  { code: 'KLK', name: 'Kalka', state: 'Himachal Pradesh', platforms: 3, zone: 'NR' },
  { code: 'UHL', name: 'Una Himachal', state: 'Himachal Pradesh', platforms: 2, zone: 'NR' },
  { code: 'RNC', name: 'Ranchi', state: 'Jharkhand', platforms: 6, zone: 'SER' },
  { code: 'DHN', name: 'Dhanbad', state: 'Jharkhand', platforms: 8, zone: 'ECR' },
  { code: 'BKSC', name: 'Bokaro Steel City', state: 'Jharkhand', platforms: 3, zone: 'SER' },
  { code: 'HZBN', name: 'Hazaribagh Town', state: 'Jharkhand', platforms: 2, zone: 'ECR' },
  { code: 'MAQ', name: 'Mangaluru Central', state: 'Karnataka', platforms: 5, zone: 'SR' },
  { code: 'BGM', name: 'Belagavi', state: 'Karnataka', platforms: 3, zone: 'SWR' },
  { code: 'SMET', name: 'Shivamogga', state: 'Karnataka', platforms: 3, zone: 'SWR' },
  { code: 'CLT', name: 'Kozhikode', state: 'Kerala', platforms: 4, zone: 'SR' },
  { code: 'KTYM', name: 'Kottayam', state: 'Kerala', platforms: 3, zone: 'SR' },
  { code: 'CAN', name: 'Kannur', state: 'Kerala', platforms: 3, zone: 'SR' },
  { code: 'DR', name: 'Dadar', state: 'Maharashtra', platforms: 8, zone: 'CR' },
  { code: 'NK', name: 'Nashik Road', state: 'Maharashtra', platforms: 4, zone: 'CR' },
  { code: 'AWB', name: 'Aurangabad', state: 'Maharashtra', platforms: 3, zone: 'SCR' },
  { code: 'JBM', name: 'Jiribam', state: 'Manipur', platforms: 2, zone: 'NFR' },
  { code: 'MNDP', name: 'Mendipathar', state: 'Meghalaya', platforms: 2, zone: 'NFR' },
  { code: 'BHRB', name: 'Bairabi', state: 'Mizoram', platforms: 2, zone: 'NFR' },
  { code: 'DMV', name: 'Dimapur', state: 'Nagaland', platforms: 3, zone: 'NFR' },
  { code: 'PURI', name: 'Puri', state: 'Odisha', platforms: 8, zone: 'ECoR' },
  { code: 'SBP', name: 'Sambalpur', state: 'Odisha', platforms: 4, zone: 'ECoR' },
  { code: 'BLS', name: 'Balasore', state: 'Odisha', platforms: 4, zone: 'SER' },
  { code: 'LDH', name: 'Ludhiana', state: 'Punjab', platforms: 7, zone: 'NR' },
  { code: 'JUC', name: 'Jalandhar City', state: 'Punjab', platforms: 5, zone: 'NR' },
  { code: 'PTK', name: 'Pathankot', state: 'Punjab', platforms: 4, zone: 'NR' },
  { code: 'BTI', name: 'Bathinda', state: 'Punjab', platforms: 6, zone: 'NR' },
  { code: 'JU', name: 'Jodhpur', state: 'Rajasthan', platforms: 5, zone: 'NWR' },
  { code: 'UDZ', name: 'Udaipur City', state: 'Rajasthan', platforms: 4, zone: 'NWR' },
  { code: 'AII', name: 'Ajmer', state: 'Rajasthan', platforms: 4, zone: 'NWR' },
  { code: 'BKN', name: 'Bikaner', state: 'Rajasthan', platforms: 5, zone: 'NWR' },
  { code: 'TEN', name: 'Tirunelveli', state: 'Tamil Nadu', platforms: 5, zone: 'SR' },
  { code: 'KCG', name: 'Kacheguda', state: 'Telangana', platforms: 5, zone: 'SCR' },
  { code: 'AGTL', name: 'Agartala', state: 'Tripura', platforms: 3, zone: 'NFR' },
  { code: 'DMR', name: 'Dharmanagar', state: 'Tripura', platforms: 2, zone: 'NFR' },
  { code: 'UDPT', name: 'Udaipur Tripura', state: 'Tripura', platforms: 2, zone: 'NFR' },
  { code: 'PRYJ', name: 'Prayagraj Junction', state: 'Uttar Pradesh', platforms: 10, zone: 'NCR' },
  { code: 'MTJ', name: 'Mathura Junction', state: 'Uttar Pradesh', platforms: 9, zone: 'NCR' },
  { code: 'DDN', name: 'Dehradun', state: 'Uttarakhand', platforms: 5, zone: 'NR' },
  { code: 'HW', name: 'Haridwar', state: 'Uttarakhand', platforms: 6, zone: 'NR' },
  { code: 'KGM', name: 'Kathgodam', state: 'Uttarakhand', platforms: 3, zone: 'NER' },
  { code: 'RKSH', name: 'Rishikesh', state: 'Uttarakhand', platforms: 3, zone: 'NR' },
  { code: 'NJP', name: 'New Jalpaiguri', state: 'West Bengal', platforms: 6, zone: 'NFR' },
  { code: 'DGR', name: 'Durgapur', state: 'West Bengal', platforms: 5, zone: 'ER' },
  { code: 'ASN', name: 'Asansol', state: 'West Bengal', platforms: 7, zone: 'ER' },
  { code: 'NZM', name: 'Hazrat Nizamuddin', state: 'Unknown', platforms: 1, zone: 'Unknown' },
  { code: 'TBM', name: 'Tambaram', state: 'Unknown', platforms: 1, zone: 'Unknown' },
  { code: 'BNC', name: 'Bengaluru Cantonment', state: 'Unknown', platforms: 1, zone: 'Unknown' },
  { code: 'SHM', name: 'Santragachi Junction', state: 'Unknown', platforms: 1, zone: 'Unknown' },
  { code: 'MLDT', name: 'Malda Town', state: 'Unknown', platforms: 1, zone: 'Unknown' },
  { code: 'ALLP', name: 'Alappuzha', state: 'Unknown', platforms: 1, zone: 'Unknown' }
];
