export const indianStations = [
  { code: 'NDLS', name: 'New Delhi', state: 'Delhi', platforms: 16, zone: 'NR' },
  { code: 'MMCT', name: 'Mumbai Central', state: 'Maharashtra', platforms: 9, zone: 'WR' },
  { code: 'CSMT', name: 'Chhatrapati Shivaji Maharaj Terminus', state: 'Maharashtra', platforms: 18, zone: 'CR' },
  { code: 'HWH', name: 'Howrah Junction', state: 'West Bengal', platforms: 23, zone: 'ER' },
  { code: 'SBC', name: 'KSR Bengaluru City', state: 'Karnataka', platforms: 10, zone: 'SWR' },
  { code: 'MAS', name: 'MGR Chennai Central', state: 'Tamil Nadu', platforms: 17, zone: 'SR' },
  { code: 'ADI', name: 'Ahmedabad Junction', state: 'Gujarat', platforms: 12, zone: 'WR' },
  { code: 'PNBE', name: 'Patna Junction', state: 'Bihar', platforms: 10, zone: 'ECR' },
  { code: 'JAT', name: 'Jammu Tawi', state: 'Jammu & Kashmir', platforms: 5, zone: 'NR' },
  { code: 'JP', name: 'Jaipur Junction', state: 'Rajasthan', platforms: 7, zone: 'NWR' },
  { code: 'HYB', name: 'Hyderabad Deccan Nampally', state: 'Telangana', platforms: 6, zone: 'SCR' },
  { code: 'SC', name: 'Secunderabad Junction', state: 'Telangana', platforms: 10, zone: 'SCR' },
  { code: 'CNB', name: 'Kanpur Central', state: 'Uttar Pradesh', platforms: 10, zone: 'NCR' },
  { code: 'GKP', name: 'Gorakhpur Junction', state: 'Uttar Pradesh', platforms: 10, zone: 'NER' },
  { code: 'BSB', name: 'Varanasi Junction', state: 'Uttar Pradesh', platforms: 9, zone: 'NR' },
  { code: 'LKO', name: 'Lucknow Charbagh NR', state: 'Uttar Pradesh', platforms: 9, zone: 'NR' },
  { code: 'CBE', name: 'Coimbatore Junction', state: 'Tamil Nadu', platforms: 6, zone: 'SR' },
  { code: 'TVC', name: 'Thiruvananthapuram Central', state: 'Kerala', platforms: 5, zone: 'SR' },
  { code: 'GHY', name: 'Guwahati Junction', state: 'Assam', platforms: 7, zone: 'NFR' },
  { code: 'BPL', name: 'Bhopal Junction', state: 'Madhya Pradesh', platforms: 6, zone: 'WCR' },
  { code: 'PUNE', name: 'Pune Junction', state: 'Maharashtra', platforms: 6, zone: 'CR' },
  { code: 'NGP', name: 'Nagpur Junction', state: 'Maharashtra', platforms: 8, zone: 'CR' },
  { code: 'BBS', name: 'Bhubaneswar', state: 'Odisha', platforms: 6, zone: 'ECoR' },
  { code: 'VSKP', name: 'Visakhapatnam Junction', state: 'Andhra Pradesh', platforms: 8, zone: 'ECoR' },
  { code: 'BZA', name: 'Vijayawada Junction', state: 'Andhra Pradesh', platforms: 10, zone: 'SCR' },
  { code: 'ASR', name: 'Amritsar Junction', state: 'Punjab', platforms: 7, zone: 'NR' },
  { code: 'CDG', name: 'Chandigarh Junction', state: 'Union Territory', platforms: 6, zone: 'NR' },
  { code: 'LTT', name: 'Lokmanya Tilak Terminus', state: 'Maharashtra', platforms: 5, zone: 'CR' },
  { code: 'KYN', name: 'Kalyan Junction', state: 'Maharashtra', platforms: 8, zone: 'CR' },
  { code: 'BDTS', name: 'Bandra Terminus', state: 'Maharashtra', platforms: 7, zone: 'WR' },
  { code: 'TATA', name: 'Tatanagar Junction', state: 'Jharkhand', platforms: 6, zone: 'SER' },
  { code: 'KGP', name: 'Kharagpur Junction', state: 'West Bengal', platforms: 12, zone: 'SER' },
  { code: 'SDAH', name: 'Sealdah', state: 'West Bengal', platforms: 21, zone: 'ER' },
  { code: 'KOAA', name: 'Kolkata', state: 'West Bengal', platforms: 5, zone: 'ER' },
  { code: 'MS', name: 'Chennai Egmore', state: 'Tamil Nadu', platforms: 11, zone: 'SR' },
  { code: 'MDU', name: 'Madurai Junction', state: 'Tamil Nadu', platforms: 8, zone: 'SR' },
  { code: 'ERS', name: 'Ernakulam Junction', state: 'Kerala', platforms: 6, zone: 'SR' },
  { code: 'AGC', name: 'Agra Cantt', state: 'Uttar Pradesh', platforms: 6, zone: 'NCR' },
  { code: 'VGLJ', name: 'VGL Jhansi Junction', state: 'Uttar Pradesh', platforms: 8, zone: 'NCR' },
  { code: 'KOTA', name: 'Kota Junction', state: 'Rajasthan', platforms: 4, zone: 'WCR' },
  { code: 'RTM', name: 'Ratlam Junction', state: 'Madhya Pradesh', platforms: 7, zone: 'WR' },
  { code: 'BRC', name: 'Vadodara Junction', state: 'Gujarat', platforms: 7, zone: 'WR' },
  { code: 'SUR', name: 'Solapur Junction', state: 'Maharashtra', platforms: 5, zone: 'CR' },
  { code: 'ET', name: 'Itarsi Junction', state: 'Madhya Pradesh', platforms: 7, zone: 'WCR' },
  { code: 'JBP', name: 'Jabalpur Junction', state: 'Madhya Pradesh', platforms: 6, zone: 'WCR' },
  { code: 'DDU', name: 'Pt Deen Dayal Upadhyaya Junction', state: 'Uttar Pradesh', platforms: 8, zone: 'ECR' },
  { code: 'GAYA', name: 'Gaya Junction', state: 'Bihar', platforms: 9, zone: 'ECR' },
  { code: 'R', name: 'Raipur Junction', state: 'Chhattisgarh', platforms: 7, zone: 'SECR' },
  { code: 'BSP', name: 'Bilaspur Junction', state: 'Chhattisgarh', platforms: 8, zone: 'SECR' },
  { code: 'DLI', name: 'Old Delhi Junction', state: 'Delhi', platforms: 16, zone: 'NR' },
  { code: 'ANVT', name: 'Anand Vihar Terminal', state: 'Delhi', platforms: 7, zone: 'NR' },
  { code: 'GZB', name: 'Ghaziabad Junction', state: 'Uttar Pradesh', platforms: 6, zone: 'NR' },
  { code: 'DNR', name: 'Danapur', state: 'Bihar', platforms: 6, zone: 'ECR' },
  { code: 'BJU', name: 'Barauni Junction', state: 'Bihar', platforms: 9, zone: 'ECR' },
  { code: 'MFP', name: 'Muzaffarpur Junction', state: 'Bihar', platforms: 6, zone: 'ECR' },
  { code: 'CPR', name: 'Chhapra Junction', state: 'Bihar', platforms: 8, zone: 'NER' },
  { code: 'GWL', name: 'Gwalior Junction', state: 'Madhya Pradesh', platforms: 4, zone: 'NCR' },
  { code: 'UJN', name: 'Ujjain Junction', state: 'Madhya Pradesh', platforms: 8, zone: 'WR' },
  { code: 'INDB', name: 'Indore Junction', state: 'Madhya Pradesh', platforms: 6, zone: 'WR' },
  { code: 'ST', name: 'Surat', state: 'Gujarat', platforms: 4, zone: 'WR' },
  { code: 'ANND', name: 'Anand Junction', state: 'Gujarat', platforms: 6, zone: 'WR' },
  { code: 'NVS', name: 'Navsari', state: 'Gujarat', platforms: 3, zone: 'WR' },
  { code: 'VAPI', name: 'Vapi', state: 'Gujarat', platforms: 3, zone: 'WR' },
  { code: 'BL', name: 'Valsad', state: 'Gujarat', platforms: 3, zone: 'WR' },
  { code: 'YPR', name: 'Yesvantpur Junction', state: 'Karnataka', platforms: 6, zone: 'SWR' },
  { code: 'MYS', name: 'Mysuru Junction', state: 'Karnataka', platforms: 6, zone: 'SWR' },
  { code: 'UBL', name: 'SSS Hubballi Junction', state: 'Karnataka', platforms: 8, zone: 'SWR' },
  { code: 'MAS-S', name: 'Tambaram', state: 'Tamil Nadu', platforms: 8, zone: 'SR' },
  { code: 'TPJ', name: 'Tiruchchirappalli Junction', state: 'Tamil Nadu', platforms: 8, zone: 'SR' },
  { code: 'ED', name: 'Erode Junction', state: 'Tamil Nadu', platforms: 4, zone: 'SR' },
  { code: 'SA', name: 'Salem Junction', state: 'Tamil Nadu', platforms: 5, zone: 'SR' },
  { code: 'TCR', name: 'Thrissur', state: 'Kerala', platforms: 4, zone: 'SR' },
  { code: 'QLN', name: 'Kollam Junction', state: 'Kerala', platforms: 6, zone: 'SR' },
  { code: 'PGT', name: 'Palakkad Junction', state: 'Kerala', platforms: 5, zone: 'SR' },
  { code: 'SRR', name: 'Shoranur Junction', state: 'Kerala', platforms: 7, zone: 'SR' },
  { code: 'AWY', name: 'Aluva', state: 'Kerala', platforms: 3, zone: 'SR' },
  { code: 'RU', name: 'Renigunta Junction', state: 'Andhra Pradesh', platforms: 5, zone: 'SCR' },
  { code: 'TPTY', name: 'Tirupati', state: 'Andhra Pradesh', platforms: 5, zone: 'SCR' },
  { code: 'NLR', name: 'Nellore', state: 'Andhra Pradesh', platforms: 4, zone: 'SCR' },
  { code: 'OGL', name: 'Ongole', state: 'Andhra Pradesh', platforms: 3, zone: 'SCR' },
  { code: 'TEL', name: 'Tenali Junction', state: 'Andhra Pradesh', platforms: 5, zone: 'SCR' },
  { code: 'WL', name: 'Warangal', state: 'Telangana', platforms: 3, zone: 'SCR' },
  { code: 'KZJ', name: 'Kazipet Junction', state: 'Telangana', platforms: 3, zone: 'SCR' },
  { code: 'BPQ', name: 'Balharshah Junction', state: 'Maharashtra', platforms: 5, zone: 'CR' },
  { code: 'SEGM', name: 'Sewagram Junction', state: 'Maharashtra', platforms: 5, zone: 'CR' },
  { code: 'BSL', name: 'Bhusaval Junction', state: 'Maharashtra', platforms: 8, zone: 'CR' },
  { code: 'JSG', name: 'Jharsuguda Junction', state: 'Odisha', platforms: 5, zone: 'SER' },
  { code: 'ROU', name: 'Rourkela Junction', state: 'Odisha', platforms: 5, zone: 'SER' },
  { code: 'CTC', name: 'Cuttack', state: 'Odisha', platforms: 5, zone: 'ECoR' },
  { code: 'BAM', name: 'Brahmapur', state: 'Odisha', platforms: 4, zone: 'ECoR' },
  { code: 'VZM', name: 'Vizianagaram Junction', state: 'Andhra Pradesh', platforms: 5, zone: 'ECoR' },
  { code: 'RJY', name: 'Rajahmundry', state: 'Andhra Pradesh', platforms: 3, zone: 'ECoR' },
  { code: 'SPJ', name: 'Samastipur Junction', state: 'Bihar', platforms: 7, zone: 'ECR' },
  { code: 'DBG', name: 'Darbhanga Junction', state: 'Bihar', platforms: 5, zone: 'ECR' },
  { code: 'GD', name: 'Gonda Junction', state: 'Uttar Pradesh', platforms: 5, zone: 'NER' },
  { code: 'DEC', name: 'Delhi Cantt', state: 'Delhi', platforms: 4, zone: 'NR' }
];
